version: '3.4'

services:
  automated.apisandbox:
    container_name: automatedapisandbox
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9000:80"
    volumes:
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
